import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { LONG_FORM_MODEL, LONG_FORM_PROJECT_TYPE, createFreeThumbnail, findPexelsAssets, parseLongFormMetadata } from "@/lib/longFormMarketing";
import { logCodeVideoPipelineEvent, upsertCodeVideoPipelineStep } from "@/lib/video-code/logger";

export const dynamic = "force-dynamic";
function object(text: string) { try { return JSON.parse(text); } catch { const a = text.indexOf("{"); const b = text.lastIndexOf("}"); if (a >= 0 && b > a) try { return JSON.parse(text.slice(a, b + 1)); } catch {} return null; } }
function scenes(raw: any[], duration: number, assets: Array<{ url: string }>) { const allowed = new Set(["TitleScene", "BulletListScene", "TimelineScene", "CodeTypingScene", "ChartScene", "BigNumberScene", "CircleHighlightScene", "RetentionScene"]); const input = Array.isArray(raw) ? raw.slice(0, 70) : []; const fallback = [{ sceneTemplate: "TitleScene", durationSec: 18, props: { title: "Marketing digital sem enrolacao", subtitle: "Aula completa" } }, { sceneTemplate: "BulletListScene", durationSec: 25, props: { title: "O que voce vai aprender", items: ["Estrategia", "Execucao", "Proximos passos"] } }]; const selected = input.length ? input : fallback; const base = selected.map((scene, index) => { const template = allowed.has(scene?.sceneTemplate) ? scene.sceneTemplate : "BulletListScene"; const media = assets[index % Math.max(assets.length, 1)]?.url; const seconds = Math.min(18, Math.max(6, Number(scene?.durationSec) || 10)); const props = { ...(scene?.props || {}), backgroundColor: index % 2 ? "#111111" : "#080808", textColor: "#ffffff", accentColor: "#dc2626", fontFamily: "Arial Black, Arial" }; if (template === "RetentionScene" && media) props.url = media; if (template === "RetentionScene" && !media) return { id: `scene-${index + 1}`, sceneTemplate: "BulletListScene", durationSec: seconds, props: { ...props, title: props.title || "Ponto importante", items: Array.isArray(props.items) ? props.items : [props.subtitle || "Aplique este passo"] } }; return { id: `scene-${index + 1}`, sceneTemplate: template, durationSec: seconds, props }; });
  const total = base.reduce((sum, scene) => sum + scene.durationSec, 0); const multiplier = duration / Math.max(total, 1); return base.map((scene) => ({ ...scene, durationSec: Math.min(22, Math.max(6, Math.round(scene.durationSec * multiplier))) })); }

export async function POST(_: NextRequest, ctx: { params: { id: string } }) {
  const project = await prisma.codeVideoProject.findFirst({ where: { id: ctx.params.id, projectType: LONG_FORM_PROJECT_TYPE } });
  if (!project) return NextResponse.json({ error: "Nao encontrado" }, { status: 404 });
  const meta = parseLongFormMetadata(project.metadataJson); if (meta.subtopics?.length < 4) return NextResponse.json({ error: "Briefing sem subtitulos suficientes." }, { status: 400 });
  const key = process.env.OPENAI_API_KEY; if (!key) return NextResponse.json({ error: "OPENAI_API_KEY nao configurada" }, { status: 400 });
  await prisma.codeVideoProject.update({ where: { id: project.id }, data: { status: "GENERATING", errorMessage: null } });
  await upsertCodeVideoPipelineStep({ projectId: project.id, stepName: "LONG_FORM_PLAN", status: "RUNNING", attempt: 1, startedAt: new Date() });
  const system = "Voce e estrategista de marketing digital, professor e diretor de arte para aulas de YouTube em portugues brasileiro. Responda somente JSON valido. Nao prometa resultados garantidos, renda facil ou burlar plataformas. Ensine de verdade todos os topicos. narrationText deve conter apenas texto falado, sem rubricas. Gere titulo honesto mas muito curioso, descricao SEO, tags, capitulos, thumbnailConcepts e scenes. Para scenes use apenas TitleScene, BulletListScene, TimelineScene, CodeTypingScene, ChartScene, BigNumberScene, CircleHighlightScene ou RetentionScene. Cada scene dura 6 a 18 segundos; props deve ter textos curtos e claros. Inclua pexelsQueries em ingles.";
  const user = JSON.stringify({ stage: meta.funnelStage, title: project.ideaPrompt, subtopics: meta.subtopics, audience: meta.audience || "iniciante em marketing digital", objective: meta.objective || "educar", cta: meta.cta || "Inscreva-se para aprender marketing digital sem enrolacao.", targetSeconds: 600, required: { narrationWords: "1150-1450", titleOptions: 3, thumbnailConcepts: 3, tags: "10-20", scenes: "40-70", chapters: "4-10" } });
  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${key}` }, body: JSON.stringify({ model: LONG_FORM_MODEL, temperature: 0.55, response_format: { type: "json_object" }, messages: [{ role: "system", content: system }, { role: "user", content: user }] }) });
    const data = await response.json(); if (!response.ok) throw new Error(data?.error?.message || "Falha na OpenAI"); const result = object(String(data?.choices?.[0]?.message?.content || "")); if (!result) throw new Error("A IA nao retornou JSON valido.");
    const queries = Array.isArray(result.pexelsQueries) ? result.pexelsQueries.map(String) : meta.subtopics.slice(0, 6).map((topic) => `digital marketing ${topic}`);
    const assets = await findPexelsAssets(queries, project.useExternalMedia); const visualScenes = scenes(result.scenes, 600, assets);
    const titleOptions = Array.isArray(result.titleOptions) ? result.titleOptions.map(String).filter(Boolean).slice(0, 3) : [String(result.title || project.title)]; const title = titleOptions[0].slice(0, 100);
    const tags = Array.isArray(result.tags) ? result.tags.map(String).filter(Boolean).slice(0, 20) : [];
    const chapters = Array.isArray(result.chapters) ? result.chapters.map((x: any, index: number) => ({ title: String(x.title || `Capitulo ${index + 1}`), startSec: Math.max(0, Number(x.startSec || index * 60)) })).slice(0, 10) : [];
    const description = [String(result.description || ""), "", "Capitulos:", ...chapters.map((c: { title: string; startSec: number }) => `${String(Math.floor(c.startSec / 60)).padStart(2, "0")}:${String(c.startSec % 60).padStart(2, "0")} ${c.title}`), "", "Conteudo educacional sobre marketing digital."].join("\n").slice(0, 4500);
    const nextMeta = { ...meta, titleOptions, selectedTitle: title, youtubeTags: tags, chapters, thumbnailConcepts: Array.isArray(result.thumbnailConcepts) ? result.thumbnailConcepts.slice(0, 3) : [], assetCredits: assets, planningApproved: false, actualCostUsd: null };
    const thumbUrl = await createFreeThumbnail(project.id, title, nextMeta);
    const updated = await prisma.codeVideoProject.update({ where: { id: project.id }, data: { status: "READY", title, description, narrationText: String(result.narrationText || "").trim(), thumbUrl, metadataJson: JSON.stringify(nextMeta), videoSpecJson: JSON.stringify({ version: 1, meta: { aspectRatio: "16:9", fps: 30, theme: { id: "marketing-red-black", name: "Marketing Red", backgroundColor: "#080808", textColor: "#ffffff", accentColor: "#dc2626", secondaryColor: "#111111", surfaceColor: "#1f1f1f", fontFamily: "Arial Black, Arial" } }, content: { title, description, narrationText: String(result.narrationText || "").trim() }, scenes: visualScenes }) } });
    await upsertCodeVideoPipelineStep({ projectId: project.id, stepName: "LONG_FORM_PLAN", status: "SUCCESS", attempt: 1, finishedAt: new Date(), responsePayload: { model: LONG_FORM_MODEL, scenes: visualScenes.length, assets: assets.length, usage: data?.usage || null } }); await logCodeVideoPipelineEvent({ projectId: project.id, stepName: "LONG_FORM_PLAN", message: `Roteiro longo, ${visualScenes.length} cenas e capa gratuita criados com ${LONG_FORM_MODEL}.` });
    return NextResponse.json(updated);
  } catch (error: any) { const message = error?.message || "Falha no planejamento"; await prisma.codeVideoProject.update({ where: { id: project.id }, data: { status: "FAILED", errorMessage: message } }); await upsertCodeVideoPipelineStep({ projectId: project.id, stepName: "LONG_FORM_PLAN", status: "FAILED", attempt: 1, finishedAt: new Date(), errorMessage: message }); return NextResponse.json({ error: message }, { status: 500 }); }
}
