import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const guides = {
  "aprender-programacao-do-zero": { title: "Como aprender programação do zero: um roteiro prático para iniciantes", description: "Entenda o que estudar primeiro para aprender programação do zero, evitar conteúdo solto e começar a construir seus primeiros projetos.", intro: "Aprender programação do zero parece confuso porque há linguagens, frameworks e ferramentas demais. A melhor forma de começar não é escolher tudo: é seguir uma ordem que construa entendimento.", steps: ["Comece por lógica: variáveis, condições, repetições e funções.", "Escolha uma linguagem para praticar os fundamentos; na formação, o caminho começa em C#.", "Crie pequenos exercícios antes de tentar um projeto grande.", "Aprenda a usar Git, banco de dados e APIs quando a base estiver firme.", "Publique um projeto e revise o que faria diferente."], body: ["O início fica mais leve quando cada estudo responde a uma pergunta concreta: como guardar uma informação, como escolher uma ação e como repetir uma tarefa. Antes de buscar a ferramenta da moda, construa essa base.", "Um projeto pequeno é melhor que dez vídeos assistidos. Uma calculadora, uma lista de tarefas simples ou uma API de livros dão contexto aos fundamentos e mostram onde suas dúvidas realmente estão."], cta: "Veja a trilha completa de programação para iniciantes" },
  "logica-de-programacao": { title: "Lógica de programação para iniciantes: o que estudar primeiro", description: "Um guia de lógica de programação para iniciantes: conceitos essenciais, ordem de estudo e como praticar antes de avançar para projetos maiores.", intro: "Lógica de programação é a habilidade de quebrar um problema em passos claros. Ela vem antes de frameworks e torna a próxima linguagem muito mais fácil de entender.", steps: ["Variáveis e tipos de dados: guardar e transformar informação.", "Condições: decidir o que acontece em cada cenário.", "Repetições: automatizar tarefas que seguem uma regra.", "Funções: nomear e reutilizar uma solução.", "Estruturas de dados: organizar listas e relações simples."], body: ["A lógica não depende de uma linguagem específica. Quando você entende o raciocínio, muda a sintaxe sem precisar recomeçar do zero. Por isso vale praticar com problemas pequenos e explicar a solução em voz alta.", "Evite pular direto para orientação a objetos, banco de dados ou inteligência artificial. Esses assuntos ficam muito mais claros quando condições, laços e funções já são naturais."], cta: "Comece pela trilha de fundamentos" },
  "csharp-para-iniciantes": { title: "C# para iniciantes: roadmap do básico à primeira API", description: "Veja o que estudar em C# para iniciantes, da lógica e orientação a objetos à criação de uma Web API com .NET.", intro: "C# é uma linguagem sólida para começar quando o objetivo é aprender fundamentos e chegar a aplicações de backend. O ganho vem de praticar numa sequência que evolui do código simples para uma API real.", steps: ["Domine sintaxe, variáveis, condições, laços e funções.", "Aprenda orientação a objetos, interfaces e abstração.", "Use coleções, arquivos, LINQ e tratamento de erros.", "Construa uma API com .NET, CRUD e banco de dados.", "Adicione autenticação, organização de camadas e publicação."], body: ["C# é usado em APIs, sistemas corporativos, automações e aplicações web. O importante no começo não é cobrir toda a plataforma .NET, mas usar a linguagem para resolver problemas e aprender a depurar.", "A primeira API é um marco prático: ela conecta rotas, regras, banco de dados e autenticação. Esse projeto mostra como as peças de um sistema trabalham juntas."], cta: "Conheça a formação com C# e .NET" },
  "curso-backend-para-iniciantes": { title: "Curso de backend para iniciantes: o que aprender antes da primeira API", description: "Saiba o que um iniciante precisa aprender para começar no backend: lógica, linguagem, APIs, banco de dados e autenticação.", intro: "Backend é a parte que recebe requisições, aplica regras e conversa com dados. Antes de montar uma API, vale entender a base que torna cada decisão menos mecânica.", steps: ["Pratique lógica e uma linguagem de programação.", "Entenda HTTP, rotas, requisições e respostas.", "Modele dados e use um banco relacional.", "Implemente CRUD e validação.", "Adicione autenticação e organize o projeto em camadas."], body: ["Um curso de backend útil não deveria começar só com copiar endpoints. A pessoa precisa entender por que uma rota existe, onde a regra de negócio fica e como proteger os dados.", "C# e .NET são uma combinação consistente para esse percurso porque permitem sair de exercícios simples para uma Web API profissional com Entity Framework."], cta: "Ver a trilha de backend com .NET" },
  "o-que-e-backend": { title: "O que é backend: guia para quem está começando em programação", description: "Entenda o que é backend, o que um desenvolvedor backend faz e quais conhecimentos estudar para começar na área.", intro: "Backend é a camada de uma aplicação que lida com regras, dados, autenticação e integrações. Quando um usuário faz login ou salva um pedido, é o backend que processa a operação.", steps: ["Aprenda uma linguagem como C#.", "Conheça HTTP e APIs REST.", "Estude banco de dados e SQL.", "Pratique autenticação e autorização.", "Aprenda a publicar e observar uma aplicação."], body: ["Frontend e backend não são adversários: uma interface usa os dados e regras disponibilizados por um backend. Entender essa ligação ajuda a escolher projetos melhores para estudar.", "Para iniciantes, o objetivo não é memorizar arquitetura avançada, mas desenvolver uma API pequena, segura e compreensível."], cta: "Conheça o caminho de fundamentos ao backend" },
  "frontend-ou-backend": { title: "Frontend ou backend: qual área estudar primeiro?", description: "Entenda a diferença entre frontend e backend, os projetos de cada área e como um iniciante pode escolher um ponto de partida.", intro: "Frontend cuida da interface que a pessoa usa; backend cuida de regras, dados e integrações. Os dois lados se conectam, e a melhor escolha inicial depende do tipo de problema que você quer resolver.", steps: ["Entenda como interface, API e banco de dados se relacionam.", "Escolha uma trilha inicial, sem tentar dominar tudo de uma vez.", "Pratique lógica e uma linguagem de programação.", "Construa um projeto simples com foco escolhido.", "Depois amplie a visão para a outra camada."], body: ["Quem gosta de interfaces, experiência visual e interação pode se identificar primeiro com frontend. Quem gosta de regras, estrutura, dados e integrações pode se identificar mais com backend.", "Mesmo escolhendo um foco, conhecer o fluxo completo torna o desenvolvedor mais capaz de conversar sobre produtos e construir projetos reais."], cta: "Ver a formação que conecta fundamentos, backend e aplicações" },
  "primeiros-projetos-de-programacao": { title: "Primeiros projetos de programação: 7 ideias para iniciantes praticarem", description: "Veja ideias de projetos de programação para iniciantes e saiba como usá-las para evoluir da lógica ao primeiro projeto com API.", intro: "Projetos pequenos transformam teoria em prática. Eles funcionam melhor quando cada um tem um objetivo limitado e permite revisar o código depois.", steps: ["Calculadora de despesas simples.", "Lista de tarefas no terminal.", "Sistema de notas de alunos.", "Gerador de senha com regras.", "API de livros ou filmes.", "Cadastro com banco de dados.", "API com autenticação de usuários."], body: ["O melhor projeto iniciante não precisa ser original; ele precisa ter escopo possível. Termine uma versão básica antes de adicionar telas, integrações ou inteligência artificial.", "Ao final de cada projeto, escreva o que você aprendeu, os erros encontrados e uma melhoria futura. Isso cria repertório e material para explicar sua evolução."], cta: "Aprenda em uma trilha com projetos conectados" },
  "como-estudar-programacao": { title: "Como estudar programação: rotina prática para quem está começando", description: "Aprenda como estudar programação com consistência, exercícios, projetos e uma sequência que evita pular fundamentos.", intro: "Uma rotina de estudo de programação precisa equilibrar teoria, prática e revisão. A sensação de estar travado muitas vezes vem de consumir conteúdo sem escrever código suficiente.", steps: ["Defina uma meta pequena para a semana.", "Estude um conceito e pratique no mesmo dia.", "Resolva exercícios sem copiar a resposta.", "Revise erros e anote padrões de dúvida.", "Feche a semana com uma pequena entrega."], body: ["Não existe quantidade mágica de horas. Consistência e feedback importam mais: estudar algumas vezes por semana, testar o que aprendeu e voltar aos erros produz mais resultado que maratonas isoladas.", "Evite alternar entre muitas linguagens no início. Uma sequência organizada reduz a carga mental e deixa claro qual habilidade vem depois."], cta: "Ver uma sequência pronta para estudar programação" },
  "csharp-ou-python-para-iniciantes": { title: "C# ou Python para iniciantes: como escolher a primeira linguagem", description: "Compare C# e Python para iniciantes e entenda como escolher uma primeira linguagem de programação sem ficar preso à decisão.", intro: "C# e Python podem servir para iniciantes. A escolha deve considerar o tipo de projeto que você quer fazer, o material disponível e principalmente se haverá uma trilha prática para seguir.", steps: ["Defina se seu foco é backend, dados, automação ou aprendizagem geral.", "Escolha uma linguagem e mantenha o foco por alguns meses.", "Aprenda lógica antes de comparar frameworks.", "Faça um projeto simples na linguagem escolhida.", "Avalie a próxima tecnologia somente depois da base."], body: ["Python costuma ter sintaxe curta e é muito presente em automação e dados. C# é uma escolha forte para quem quer evoluir para APIs, aplicações estruturadas e ecossistema .NET.", "A primeira linguagem não determina sua carreira inteira. O raciocínio, a prática e a capacidade de aprender novas ferramentas são mais duradouros que a escolha inicial."], cta: "Começar pela trilha de C# e backend" },
  "banco-de-dados-para-iniciantes": { title: "Banco de dados para iniciantes: o que estudar para usar em projetos", description: "Entenda os fundamentos de banco de dados para iniciantes: tabelas, relacionamentos, SQL, CRUD e como aplicar em uma API.", intro: "Banco de dados permite guardar e recuperar informações de uma aplicação. Ele entra no estudo de programação quando o projeto precisa persistir usuários, produtos, tarefas ou qualquer dado.", steps: ["Entenda tabelas, colunas e registros.", "Aprenda chaves primárias e relacionamentos.", "Pratique consultas SQL básicas.", "Implemente criar, ler, atualizar e excluir dados.", "Conecte uma API a um banco de dados."], body: ["O banco não deve ser visto como uma etapa isolada. Ele faz sentido quando aparece em um projeto real, onde você precisa modelar informações e proteger acessos.", "PostgreSQL e Entity Framework permitem praticar esse fluxo em projetos .NET sem abandonar a clareza do modelo de dados."], cta: "Conheça a formação com APIs e banco de dados" },
  "api-rest-para-iniciantes": { title: "API REST para iniciantes: como funciona e o que estudar primeiro", description: "Um guia de API REST para iniciantes: requisições, rotas, métodos HTTP, dados, CRUD e autenticação em projetos práticos.", intro: "Uma API REST permite que sistemas troquem informações por meio de endpoints. Ela recebe uma requisição, aplica regras e devolve uma resposta, normalmente em JSON.", steps: ["Conheça URL, endpoint, request e response.", "Aprenda GET, POST, PUT, PATCH e DELETE.", "Crie um CRUD simples.", "Valide dados e trate erros.", "Conecte banco e autenticação."], body: ["Começar por uma API pequena ajuda a visualizar o backend inteiro. Em vez de decorar verbos HTTP, faça uma aplicação de livros, tarefas ou produtos com operações reais.", "Depois do CRUD, a evolução natural é organizar camadas, adicionar autenticação e publicar a aplicação."], cta: "Aprenda a construir sua primeira Web API" },
  "roadmap-desenvolvedor-iniciante": { title: "Roadmap de desenvolvedor iniciante: do primeiro código ao projeto publicado", description: "Veja um roadmap de desenvolvedor iniciante com fundamentos, linguagem, APIs, banco de dados, arquitetura e cloud.", intro: "Um roadmap reduz a ansiedade de quem vê muitas tecnologias ao mesmo tempo. Ele não é uma lista para estudar tudo; é uma sequência que explica o motivo de cada próxima etapa.", steps: ["Lógica de programação.", "Uma linguagem e orientação a objetos.", "Git e prática com exercícios.", "APIs, HTTP e banco de dados.", "Arquitetura de software e cloud."], body: ["A ordem importa porque projetos maiores exigem conceitos anteriores. Tentar aprender cloud, microserviços ou IA sem conseguir explicar uma função e uma condição costuma atrasar a evolução.", "Use o roadmap como referência e ajuste o ritmo à sua rotina. O objetivo é construir capacidade prática, não marcar tecnologias como concluídas."], cta: "Seguir a formação organizada para iniciantes" },
  "quanto-tempo-para-aprender-programacao": { title: "Quanto tempo leva para aprender programação? Expectativa realista para iniciantes", description: "Entenda quanto tempo leva para aprender programação, quais fatores influenciam a evolução e como montar uma rotina de prática realista.", intro: "O tempo para aprender programação varia conforme a rotina, o objetivo e a qualidade da prática. Em vez de procurar uma data exata, vale definir marcos de evolução observáveis.", steps: ["Primeiro: resolver exercícios simples de lógica.", "Depois: criar programas pequenos sem tutorial completo.", "Em seguida: usar Git, banco e uma API.", "Depois: terminar um projeto publicado.", "Por fim: aprofundar arquitetura e portfólio."], body: ["Uma pessoa pode entender a base em semanas e continuar evoluindo por anos. O marco relevante não é saber tudo, mas conseguir aprender uma tecnologia nova usando princípios que já domina.", "Rotina consistente, revisão de erros e projetos concluídos aceleram mais que trocar de curso sempre que surge uma dificuldade."], cta: "Ver uma trilha prática com marcos claros" },
} as const;

type GuideSlug = keyof typeof guides;

export function generateStaticParams() { return Object.keys(guides).map((slug) => ({ slug })); }

export function generateMetadata({ params }: { params: { slug: string } }): Metadata {
  const guide = guides[params.slug as GuideSlug];
  if (!guide) return { robots: { index: false, follow: false } };
  return { title: `${guide.title} | Plugando IA`, description: guide.description, alternates: { canonical: `/guia-programacao/${params.slug}` }, robots: { index: true, follow: true }, openGraph: { title: guide.title, description: guide.description, type: "article", url: `/guia-programacao/${params.slug}` } };
}

export default function GuiaProgramacaoPage({ params }: { params: { slug: string } }) {
  const guide = guides[params.slug as GuideSlug];
  if (!guide) notFound();
  const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.description, author: { "@type": "Organization", name: "Plugando IA" }, publisher: { "@type": "Organization", name: "Plugando IA" } };
  return <main className="min-h-screen bg-[#fffdf8] text-slate-900"><article className="mx-auto max-w-3xl px-6 py-16 md:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Link href="/curso-programacao" className="text-sm font-black text-emerald-700 hover:underline">← Curso de programação para iniciantes</Link><p className="mt-10 text-sm font-black uppercase tracking-[0.18em] text-emerald-700">Guia para iniciantes</p><h1 className="mt-4 text-4xl font-black leading-tight md:text-5xl">{guide.title}</h1><p className="mt-7 text-lg leading-8 text-slate-700">{guide.intro}</p><h2 className="mt-12 text-3xl font-black">Roteiro recomendado</h2><ol className="mt-6 space-y-5">{guide.steps.map((step, index) => <li key={step} className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-700 font-black text-white">{index + 1}</span><span className="leading-7 text-slate-700">{step}</span></li>)}</ol><h2 className="mt-12 text-3xl font-black">Contexto para estudar melhor</h2>{guide.body.map((paragraph) => <p key={paragraph} className="mt-4 leading-8 text-slate-700">{paragraph}</p>)}<h2 className="mt-12 text-3xl font-black">Como transformar estudo em prática</h2><p className="mt-4 leading-8 text-slate-700">Escolha exercícios pequenos, escreva o código sem copiar a resposta e registre suas dúvidas. Quando os fundamentos fizerem sentido, avance para um projeto que conecte linguagem, banco de dados e API. A consistência vale mais do que tentar estudar todas as tecnologias ao mesmo tempo.</p><aside className="mt-12 rounded-3xl bg-slate-950 p-8 text-white"><h2 className="text-2xl font-black">{guide.cta}</h2><p className="mt-3 leading-7 text-slate-300">A Formação Plugando IA organiza essa progressão com fundamentos, C#, APIs, arquitetura e cloud.</p><Link href={`/curso-completo?utm_source=seo&utm_medium=organic&utm_campaign=${params.slug}`} className="mt-6 inline-flex rounded-xl bg-lime-300 px-5 py-3 font-black text-slate-950 hover:bg-lime-200">Ver formação completa</Link></aside></article></main>;
}
