// 30 Nichos/Categorias para YouTube Analytics
export const YT_CATEGORIES = [
  { name: "Entretenimento / Humor", slug: "entretenimento-humor", color: "#f43f5e", icon: "EmojiEmotions" },
  { name: "Games", slug: "games", color: "#8b5cf6", icon: "SportsEsports" },
  { name: "Música", slug: "musica", color: "#ec4899", icon: "MusicNote" },
  { name: "Futebol / Esportes", slug: "futebol-esportes", color: "#10b981", icon: "SportsSoccer" },
  { name: "Política / Atualidades", slug: "politica-atualidades", color: "#6366f1", icon: "Gavel" },
  { name: "Finanças / Investimentos", slug: "financas-investimentos", color: "#f59e0b", icon: "TrendingUp" },
  { name: "Tecnologia / IA", slug: "tecnologia-ia", color: "#3b82f6", icon: "Computer" },
  { name: "Educação / Aulas", slug: "educacao-aulas", color: "#14b8a6", icon: "School" },
  { name: "Curiosidades", slug: "curiosidades", color: "#a855f7", icon: "Lightbulb" },
  { name: "Podcast / Cortes", slug: "podcast-cortes", color: "#f97316", icon: "Podcasts" },
  { name: "Lifestyle / Vlog", slug: "lifestyle-vlog", color: "#06b6d4", icon: "Videocam" },
  { name: "Beleza / Moda", slug: "beleza-moda", color: "#d946ef", icon: "Face" },
  { name: "Saúde / Fitness", slug: "saude-fitness", color: "#22c55e", icon: "FitnessCenter" },
  { name: "Receitas / Culinária", slug: "receitas-culinaria", color: "#eab308", icon: "Restaurant" },
  { name: "Motivacional / Desenv. Pessoal", slug: "motivacional", color: "#0ea5e9", icon: "EmojiObjects" },
  { name: "Empreendedorismo / Mktg Digital", slug: "empreendedorismo", color: "#f43f5e", icon: "Rocket" },
  { name: "Review de Produtos", slug: "review-produtos", color: "#64748b", icon: "RateReview" },
  { name: "Canal Infantil", slug: "infantil", color: "#fbbf24", icon: "ChildCare" },
  { name: "Religião / Gospel", slug: "religiao-gospel", color: "#a78bfa", icon: "Church" },
  { name: "Mistério / Terror / Iceberg", slug: "misterio-terror", color: "#1e293b", icon: "Nightlight" },
  { name: "Cinema / Séries / Anime", slug: "cinema-series-anime", color: "#e11d48", icon: "Movie" },
  { name: "Automóveis / Motos", slug: "automoveis-motos", color: "#dc2626", icon: "DirectionsCar" },
  { name: "Viagens / Turismo", slug: "viagens-turismo", color: "#0d9488", icon: "Flight" },
  { name: "Relacionamento / Dating", slug: "relacionamento", color: "#fb7185", icon: "Favorite" },
  { name: "ASMR / Relaxamento", slug: "asmr-relaxamento", color: "#818cf8", icon: "Headphones" },
  { name: "Animais / Pets", slug: "animais-pets", color: "#84cc16", icon: "Pets" },
  { name: "História / Documentários", slug: "historia-documentarios", color: "#78716c", icon: "HistoryEdu" },
  { name: "DIY / Faça Você Mesmo", slug: "diy", color: "#fb923c", icon: "Build" },
  { name: "Memes / Shorts Virais", slug: "memes-shorts", color: "#facc15", icon: "Whatshot" },
  { name: "Luxo / Lifestyle Rico", slug: "luxo-lifestyle", color: "#d4a574", icon: "Diamond" },
];
