import "server-only";

export type SuggestedScrapingSource = {
  name: string;
  url: string;
};

export const SUGGESTED_NEWS_SCRAPING_SOURCES: SuggestedScrapingSource[] = [
  { name: "G1 Tecnologia", url: "https://g1.globo.com/tecnologia/" },
  { name: "G1 Economia", url: "https://g1.globo.com/economia/" },
  { name: "G1 Politica", url: "https://g1.globo.com/politica/" },
  { name: "G1 Mundo", url: "https://g1.globo.com/mundo/" },
  { name: "G1 Saude", url: "https://g1.globo.com/saude/" },
  { name: "G1 Carros", url: "https://g1.globo.com/carros/" },
  { name: "G1 Educacao", url: "https://g1.globo.com/educacao/" },
  { name: "G1 Agro", url: "https://g1.globo.com/economia/agronegocios/" },
  { name: "G1 Turismo", url: "https://g1.globo.com/turismo-e-viagem/" },
  { name: "Ge Globo", url: "https://ge.globo.com/" },
  { name: "Autoesporte", url: "https://autoesporte.globo.com/" },
  { name: "Globo Rural", url: "https://globorural.globo.com/" },
  { name: "Pegn Globo", url: "https://revistapegn.globo.com/" },
  { name: "Casa e Jardim", url: "https://casaejardim.globo.com/" },
  { name: "Casa Vogue", url: "https://casavogue.globo.com/" },
  { name: "Canaltech", url: "https://canaltech.com.br/" },
  { name: "Tecnoblog", url: "https://tecnoblog.net/" },
  { name: "Olhar Digital", url: "https://olhardigital.com.br/" },
  { name: "Meio Bit", url: "https://meiobit.com/" },
  { name: "Tilt UOL", url: "https://www.uol.com.br/tilt/" },
  { name: "UOL Noticias", url: "https://noticias.uol.com.br/" },
  { name: "UOL Economia", url: "https://economia.uol.com.br/" },
  { name: "UOL Esporte", url: "https://www.uol.com.br/esporte/" },
  { name: "UOL Splash", url: "https://www.uol.com.br/splash/" },
  { name: "UOL Universa", url: "https://www.uol.com.br/universa/" },
  { name: "UOL Nossa", url: "https://www.uol.com.br/nossa/" },
  { name: "UOL Carros", url: "https://www.uol.com.br/carros/" },
  { name: "Folha Mercado", url: "https://www1.folha.uol.com.br/mercado/" },
  { name: "Folha Mundo", url: "https://www1.folha.uol.com.br/mundo/" },
  { name: "Folha Equilibrio e Saude", url: "https://www1.folha.uol.com.br/equilibrioesaude/" },
  { name: "Folha Tec", url: "https://www1.folha.uol.com.br/tec/" },
  { name: "Folha Ilustrada", url: "https://www1.folha.uol.com.br/ilustrada/" },
  { name: "Folha Esporte", url: "https://www1.folha.uol.com.br/esporte/" },
  { name: "Estadao Politica", url: "https://politica.estadao.com.br/" },
  { name: "Estadao Economia", url: "https://economia.estadao.com.br/" },
  { name: "Estadao Link", url: "https://link.estadao.com.br/" },
  { name: "Estadao Internacional", url: "https://internacional.estadao.com.br/" },
  { name: "Estadao Esportes", url: "https://esportes.estadao.com.br/" },
  { name: "CNN Brasil Tecnologia", url: "https://www.cnnbrasil.com.br/tecnologia/" },
  { name: "CNN Brasil Economia", url: "https://www.cnnbrasil.com.br/economia/" },
  { name: "CNN Brasil Politica", url: "https://www.cnnbrasil.com.br/politica/" },
  { name: "CNN Brasil Internacional", url: "https://www.cnnbrasil.com.br/internacional/" },
  { name: "CNN Brasil Esportes", url: "https://www.cnnbrasil.com.br/esportes/" },
  { name: "CNN Brasil Saude", url: "https://www.cnnbrasil.com.br/saude/" },
  { name: "CNN Brasil Entretenimento", url: "https://www.cnnbrasil.com.br/entretenimento/" },
  { name: "CNN Brasil Viagem e Gastronomia", url: "https://www.cnnbrasil.com.br/viagemegastronomia/" },
  { name: "Exame Tecnologia", url: "https://exame.com/tecnologia/" },
  { name: "Exame Economia", url: "https://exame.com/economia/" },
  { name: "Exame Negocios", url: "https://exame.com/negocios/" },
  { name: "Exame Bussola", url: "https://exame.com/bussola/" },
  { name: "Valor Economico", url: "https://valor.globo.com/" },
  { name: "Agencia Brasil Politica", url: "https://agenciabrasil.ebc.com.br/politica" },
  { name: "Agencia Brasil Economia", url: "https://agenciabrasil.ebc.com.br/economia" },
  { name: "Agencia Brasil Saude", url: "https://agenciabrasil.ebc.com.br/saude" },
  { name: "Agencia Brasil Esportes", url: "https://agenciabrasil.ebc.com.br/esportes" },
  { name: "Agencia Brasil Internacional", url: "https://agenciabrasil.ebc.com.br/internacional" },
  { name: "Agencia Brasil Direitos Humanos", url: "https://agenciabrasil.ebc.com.br/direitos-humanos" },
  { name: "Agencia Brasil Educacao", url: "https://agenciabrasil.ebc.com.br/educacao" },
  { name: "InfoMoney Mercados", url: "https://www.infomoney.com.br/mercados/" },
  { name: "InfoMoney Negocios", url: "https://www.infomoney.com.br/negocios/" },
  { name: "InfoMoney Onde Investir", url: "https://www.infomoney.com.br/onde-investir/" },
  { name: "InfoMoney Consumo", url: "https://www.infomoney.com.br/consumo/" },
  { name: "Poder360", url: "https://www.poder360.com.br/" },
  { name: "R7 Tecnologia e Ciencia", url: "https://r7.com/tecnologia-e-ciencia/" },
  { name: "R7 Economia", url: "https://noticias.r7.com/economia/" },
  { name: "R7 Saude", url: "https://noticias.r7.com/saude/" },
  { name: "Terra Byte", url: "https://www.terra.com.br/byte/" },
  { name: "Terra Economia", url: "https://www.terra.com.br/economia/" },
  { name: "Terra Diversao", url: "https://www.terra.com.br/diversao/" },
  { name: "Brasil de Fato", url: "https://www.brasildefato.com.br/" },
  { name: "Nexo Jornal", url: "https://www.nexojornal.com.br/" },
  { name: "The News", url: "https://thenewscc.com.br/" },
];
