ALTER TYPE "ShopeePipelineStatus" ADD VALUE IF NOT EXISTS 'GENERATING_PLATFORM_METADATA';
ALTER TYPE "ShopeePipelineStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_SCHEDULING';

ALTER TABLE "ColetaDadosShoppe"
  ADD COLUMN IF NOT EXISTS "platformMetadata" JSONB;
