import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { TechnicalContentTracker } from "@/components/TechnicalContentTracker";

export const dynamic = "force-dynamic";

async function getPost(slug: string) { return prisma.post.findFirst({ where: { slug, status: "PUBLISHED", origin: { startsWith: "TECHNICAL_" } } }); }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const post = await getPost(params.slug); if (!post) return { robots: { index: false, follow: false } }; return { title: `${post.seoTitle || post.title} | Plugando IA`, description: post.metaDescription || post.summary, alternates: { canonical: `/artigos-tecnicos/${post.slug}` }, openGraph: { type: "article", title: post.title, description: post.summary, publishedTime: post.publishedAt?.toISOString() } }; }
function markdown(content: string) { return content.split(/\n{2,}/).map((block, index) => { const value = block.trim(); if (value.startsWith("### ")) return <h3 key={index} className="mt-8 text-xl font-bold">{value.slice(4)}</h3>; if (value.startsWith("## ")) return <h2 key={index} className="mt-10 text-3xl font-bold tracking-tight">{value.slice(3)}</h2>; if (/^[-*] /m.test(value)) return <ul key={index} className="mt-5 list-disc space-y-2 pl-6 leading-8 text-slate-700">{value.split("\n").filter((line) => /^[-*] /.test(line)).map((line) => <li key={line}>{line.replace(/^[-*] /, "")}</li>)}</ul>; return <p key={index} className="mt-5 leading-8 text-slate-700">{value.replace(/\*\*/g, "")}</p>; }); }
export default async function ArtigoTecnicoPage({ params }: { params: { slug: string } }) { const post = await getPost(params.slug); if (!post) notFound(); const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: post.title, description: post.summary, datePublished: post.publishedAt?.toISOString(), dateModified: post.updatedAt.toISOString(), author: { "@type": "Organization", name: "Plugando IA" }, publisher: { "@type": "Organization", name: "Plugando IA" } }; return <main className="min-h-screen bg-white text-slate-950"><TechnicalContentTracker page="article" postId={post.id} /><article className="mx-auto max-w-3xl px-5 py-14 md:py-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Link href="/artigos-tecnicos" className="text-sm font-bold text-blue-700">← Artigos técnicos</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.14em] text-blue-700">{post.origin.replace("TECHNICAL_", "")} de funil</p><h1 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight text-[#0b1f3a] md:text-5xl">{post.title}</h1><p className="mt-6 text-xl leading-8 text-slate-600">{post.summary}</p><div className="mt-6 border-y border-slate-200 py-3 text-sm text-slate-500">Publicado em {post.publishedAt?.toLocaleDateString("pt-BR")}</div><div className="mt-8">{markdown(post.content)}</div><aside className="mt-12 rounded-2xl bg-[#0b1f3a] p-8 text-white"><h2 className="text-2xl font-bold">Quer transformar esse conhecimento em prática?</h2><p className="mt-3 leading-7 text-slate-300">Veja os cursos de programação, arquitetura, RabbitMQ e SaaS da Plugando IA.</p><Link href="/cursos?utm_source=artigos_tecnicos&utm_medium=organic&utm_campaign=cta_artigo" className="mt-6 inline-flex rounded-lg bg-white px-5 py-3 text-sm font-bold text-[#0b1f3a]">Conhecer os cursos</Link></aside></article></main>; }
